version: '3.8'

services:
  app:
    build:
      context: ./api  # Atualizado para o diretório correto
      dockerfile: Dockerfile
    container_name: demoblaze_site-app-qa
    ports:
      - "8000:8000"  # Porta exclusiva para QA
    environment:
      - DATABASE_URL=postgresql://demoblaze_user:Q@cdias3242*&@db:5432/demoblaze
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./frontend/static:/app/frontend/static-qa  # Volume exclusivo para QA

  db:
    image: postgres:13
    container_name: demoblaze_site-db-qa
    environment:
      - POSTGRES_USER=demoblaze_user
      - POSTGRES_PASSWORD=Q@cdias3242*&
      - POSTGRES_DB=demoblaze
    ports:
      - "5433:5432"  # Porta exclusiva para QA
    volumes:
      - postgres_data_qa:/var/lib/postgresql/data  # Volume exclusivo para QA

volumes:
  postgres_data_qa:  # Volume isolado para o banco de dados QA

networks:
  qa_network:  # Rede exclusiva para QA
    driver: bridge
