version: '3.8'

services:
  app:
    build: ./api
    container_name: demoblaze_site-app
    ports:
      - "8000:8000" 
    environment:
      - DATABASE_URL=postgresql://demoblaze_user:Q@cdias3242*&@db:5432/demoblaze
    volumes:
      - ./frontend/static:/app/frontend/static  # Mapeia o diretório de frontend para o contêiner
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:13
    container_name: demoblaze_site-db-1
    environment:
      - POSTGRES_USER=demoblaze_user
      - POSTGRES_PASSWORD=Q@cdias3242*&
      - POSTGRES_DB=demoblaze
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
