name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Instalar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build do container
        run: docker-compose up -d --build

      - name: Gerar nova versão e criar tag
        id: tag
        run: |
          git fetch --prune --unshallow
          TAG="v1.0.$(date +'%Y%m%d%H%M%S')"
          echo "Nova versão: $TAG"
          git tag $TAG
          git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Criar Release no GitHub
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.TAG }}
          release_name: "Release ${{ steps.tag.outputs.TAG }}"
          draft: false
          prerelease: false
          body: "Nova release criada automaticamente pelo CI/CD pipeline."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
