name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build do container
        run: docker-compose up -d --build

      - name: Testes com Cypress
        run: |
          docker-compose exec -T <seu_container_de_testes> npx cypress run
