name: CI/CD Pipeline

on:
  push:
    branches:
      - qa
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Instalar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build e Deploy
        run: |
          if [ "${{ github.ref }}" == "refs/heads/qa" ]; then
            echo "Deploy para QA na porta 8000"
            docker-compose -f docker-compose.yml -f docker-compose.qa.yml down
            docker-compose -f docker-compose.yml -f docker-compose.qa.yml up -d --build
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Deploy para Produção na porta 8100"
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml down
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
          fi
