name: Merge Automático para Main

on:
  repository_dispatch:  # Gatilho para eventos enviados pela automação.
    types:
      - merge-triggered

jobs:
  merge-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Garante que todas as branches sejam buscadas.

      - name: Configurar Git para o Merge
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge da branch QA para Main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout main  # Faz checkout na branch main.
          git merge qa --no-ff -m "Merge automático de QA para Main"  # Realiza o merge.
          git push origin main  # Faz push do merge para o repositório remoto.
