name: Merge Automático

on:
  repository_dispatch:
    types:
      - merge-triggered

jobs:
  merge-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Buscar todas as branches remotas
        run: |
          git fetch origin  # Busca as branches remotas
          git branch -r     # Lista as branches remotas para depuração

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge para Produção
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout main  # Garante que estamos na branch main
          git merge origin/qa --no-ff -m "Merge automático de QA para Main"  # Faz o merge
          git push origin main  # Faz push para o repositório remoto
